server:
  address: 127.0.0.1
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: #EXTERNAL
    username: #EXTERNAL
    password: #EXTERNAL
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 40
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update